; ##############################################################################
;
; Project: ICECARINT V1.0
; File Name: lcd.inc
; Processor: PIC16F914
; Frequency: 8 MHz
;
; ##############################################################################

; ------------------------------------------------------------------------------
; Variables declaration
; ------------------------------------------------------------------------------
LCDDAT0         EQU H'0030'
LCDDAT1         EQU H'0031'
LCDDAT2         EQU H'0032'
LCDDAT3         EQU H'0033'
LCDDAT4         EQU H'0034'
LCDDAT5         EQU H'0035'
LCDDAT6         EQU H'0036'
LCDDAT7         EQU H'0037'
LCDDAT8         EQU H'0038'
LCDDAT9         EQU H'0039'
LCDDATA         EQU H'003A'
LCDDATB         EQU H'003B'
LCDDATC         EQU H'003C'
LCDDATD         EQU H'003D'
LCDDATE         EQU H'003E'
LCDDATF         EQU H'003F'